# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imageGenerator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14imageGenerator.proto\x12\x0eimageGenerator\"\x07\n\x05\x45mpty\"<\n\x14GenerateImageRequest\x12\x0f\n\x07ImageId\x18\x01 \x01(\t\x12\x13\n\x0b\x42\x61sedOnText\x18\x02 \x01(\t\"$\n\x11GetGeneratedImage\x12\x0f\n\x07ImageId\x18\x01 \x01(\t\"-\n\x16GeneratedImageResponse\x12\x13\n\x0bImageBase64\x18\x01 \x01(\t2\xb5\x01\n\x0eImageGenerator\x12L\n\rGenerateImage\x12$.imageGenerator.GenerateImageRequest\x1a\x15.imageGenerator.Empty\x12U\n\x08GetImage\x12!.imageGenerator.GetGeneratedImage\x1a&.imageGenerator.GeneratedImageResponseb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_GENERATEIMAGEREQUEST = DESCRIPTOR.message_types_by_name['GenerateImageRequest']
_GETGENERATEDIMAGE = DESCRIPTOR.message_types_by_name['GetGeneratedImage']
_GENERATEDIMAGERESPONSE = DESCRIPTOR.message_types_by_name['GeneratedImageResponse']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'imageGenerator_pb2'
  # @@protoc_insertion_point(class_scope:imageGenerator.Empty)
  })
_sym_db.RegisterMessage(Empty)

GenerateImageRequest = _reflection.GeneratedProtocolMessageType('GenerateImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEIMAGEREQUEST,
  '__module__' : 'imageGenerator_pb2'
  # @@protoc_insertion_point(class_scope:imageGenerator.GenerateImageRequest)
  })
_sym_db.RegisterMessage(GenerateImageRequest)

GetGeneratedImage = _reflection.GeneratedProtocolMessageType('GetGeneratedImage', (_message.Message,), {
  'DESCRIPTOR' : _GETGENERATEDIMAGE,
  '__module__' : 'imageGenerator_pb2'
  # @@protoc_insertion_point(class_scope:imageGenerator.GetGeneratedImage)
  })
_sym_db.RegisterMessage(GetGeneratedImage)

GeneratedImageResponse = _reflection.GeneratedProtocolMessageType('GeneratedImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEDIMAGERESPONSE,
  '__module__' : 'imageGenerator_pb2'
  # @@protoc_insertion_point(class_scope:imageGenerator.GeneratedImageResponse)
  })
_sym_db.RegisterMessage(GeneratedImageResponse)

_IMAGEGENERATOR = DESCRIPTOR.services_by_name['ImageGenerator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=40
  _EMPTY._serialized_end=47
  _GENERATEIMAGEREQUEST._serialized_start=49
  _GENERATEIMAGEREQUEST._serialized_end=109
  _GETGENERATEDIMAGE._serialized_start=111
  _GETGENERATEDIMAGE._serialized_end=147
  _GENERATEDIMAGERESPONSE._serialized_start=149
  _GENERATEDIMAGERESPONSE._serialized_end=194
  _IMAGEGENERATOR._serialized_start=197
  _IMAGEGENERATOR._serialized_end=378
# @@protoc_insertion_point(module_scope)
