# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import imageGenerator_pb2 as imageGenerator__pb2


class ImageGeneratorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateImage = channel.unary_unary(
                '/imageGenerator.ImageGenerator/GenerateImage',
                request_serializer=imageGenerator__pb2.GenerateImageRequest.SerializeToString,
                response_deserializer=imageGenerator__pb2.Empty.FromString,
                )
        self.GetImage = channel.unary_unary(
                '/imageGenerator.ImageGenerator/GetImage',
                request_serializer=imageGenerator__pb2.GetGeneratedImage.SerializeToString,
                response_deserializer=imageGenerator__pb2.GeneratedImageResponse.FromString,
                )


class ImageGeneratorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageGeneratorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=imageGenerator__pb2.GenerateImageRequest.FromString,
                    response_serializer=imageGenerator__pb2.Empty.SerializeToString,
            ),
            'GetImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImage,
                    request_deserializer=imageGenerator__pb2.GetGeneratedImage.FromString,
                    response_serializer=imageGenerator__pb2.GeneratedImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageGenerator.ImageGenerator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageGenerator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageGenerator.ImageGenerator/GenerateImage',
            imageGenerator__pb2.GenerateImageRequest.SerializeToString,
            imageGenerator__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageGenerator.ImageGenerator/GetImage',
            imageGenerator__pb2.GetGeneratedImage.SerializeToString,
            imageGenerator__pb2.GeneratedImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
