// <auto-generated />
using ArtOfTime.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtOfTime.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220319155813_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArtOfTime.Data.Entities.Image", b =>
                {
                    b.Property<string>("TimeStamp")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BasedOnText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFetched")
                        .HasColumnType("bit");

                    b.HasKey("TimeStamp");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
